packages:
  - 'apps/*'
  - 'packages/*'
allowBuilds:
  prisma: true
  '@prisma/engines': true
  '@nestjs/core': true
  argon2: true
  esbuild: true
  '@scarf/scarf': false
  msw: true
  unrs-resolver: true
  '@sentry/cli': true
  '@swc/core': true
  protobufjs: false
  '@firebase/util': false
onlyBuiltDependencies:
  - prisma
  - '@prisma/engines'
  - '@nestjs/core'
  - argon2
  - esbuild
  - msw
  - unrs-resolver
  - '@sentry/cli'
  - '@swc/core'
minimumReleaseAgeExclude:
  - lucide-react@1.17.0
  - zustand@5.0.14
  - '@heejun/prettier-config@3.0.0'
  - '@heejun/eslint-config@4.0.0'
  - '@heejun/deskcloud@0.1.0'
overrides:
  electron-to-chromium: 1.5.362
  enhanced-resolve: 5.22.0
  zod@3.24.4: 3.25.76
