packages:
  - 'apps/*'
  - 'packages/*'
allowBuilds:
  prisma: true
  '@prisma/engines': true
  '@nestjs/core': true
  argon2: true
  esbuild: true
  '@scarf/scarf': false
minimumReleaseAgeExclude:
  - lucide-react@1.17.0
  - zustand@5.0.14
overrides:
  electron-to-chromium: 1.5.362
  enhanced-resolve: 5.22.0
